apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "music2web.fullname" . }}
  labels:
    {{- include "music2web.labels" . | nindent 4 }}
spec:
  serviceName: {{ .Values.serviceName }}
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "music2web.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "music2web.selectorLabels" . | nindent 8 }}
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: app.kubernetes.io/name
                operator: In
                values:
                - {{ include "music2web.name" . }}
            topologyKey: {{ .Values.podAntiAffinity.topologyKey }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "ghcr.io/marslorg/music2web:latest"
          imagePullPolicy: Always
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /health
              port: http
          readinessProbe:
            httpGet:
              path: /ready
              port: http
          startupProbe:
            httpGet:
              path: /startup
              port: http
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
          - mountPath: /var/www/html/includes/config.inc.php
            name: config-file-volume
            subPath: {{ .Values.configFile.subPath }}
          - mountPath: /var/www/html/includes/errorHandler.php
            name: error-handler-file-volume
            subPath: {{ .Values.errorHandlerFile.subPath }}
          - mountPath: /var/www/html/albums
            name: albums-vol
          - mountPath: /var/www/html/files
            name: files-vol
          - mountPath: /var/www/html/news
            name: news-vol
          - mountPath: /var/www/html/shared
            name: shared-vol
      volumes:
      - name: albums-vol
        hostPath:
          path: {{ .Values.albums.hostPath }}
          type: Directory
      - name: files-vol
        hostPath:
          path: {{ .Values.files.hostPath }}
          type: Directory
      - name: news-vol
        hostPath:
          path: {{ .Values.news.hostPath }}
          type: Directory
      - name: shared-vol
        hostPath:
          path: {{ .Values.shared.hostPath }}
          type: Directory
      - name: config-file-volume
        configMap:
          name: {{ .Values.configFile.configMap }}
      - name: error-handler-file-volume
        configMap:
          name: {{ .Values.errorHandlerFile.configMap }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
  updateStrategy:
    type: {{ .Values.updateStrategy }}
